### ISSUE TITLE
Support F# Modules

### ISSUE THREAD

**Issue by jongio** [Azure/iotedgedev#103]

**Comment by LazarusX** [comment]
The .NET Core module template supports F# (https://github.com/Azure/dotnet-template-azure-iot-edge-module/tree/master/content/dotnet-template-azure-iot-edge-module/FSharp) thanks to @WilliamBerryiii

**Comment by WilliamBerryiii** [comment]
I do need to update the module now that the modules sdk is split out.

**Comment by WilliamBerryiii** [comment]
The F# Templates have been updated to the GA bits in this PR: https://github.com/Azure/dotnet-template-azure-iot-edge-module/pull/39
