### ISSUE TITLE
Scripts report success even when Docker commands timeout

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/iotedgedev#143]
When the tool is used in constrained or spotty networks where remote network calls may timeout, the tool will return a success status even through the underlying Docker command failed.

**Comment by jonbgallant** [comment]
@WilliamBerryiii  which commands?

**Comment by WilliamBerryiii** [comment]
We mainly saw it with push and pull on remote repositories, though I'd assume any network call would be susceptible.

**Comment by jonbgallant** [comment]
So, push fails due to poor network, but the tool reports success?

**Comment by WilliamBerryiii** [comment]
Yup ... I can't fine the log statement that I copied when I found it ... need to make a repro.

**Comment by LazarusX** [comment]
Possibly resolved by https://github.com/Azure/iotedgedev/pull/240. I'll close it due to inactivity, but feel free to reopen if you can still reproduce this issue after https://github.com/Azure/iotedgedev/pull/240 is released.
