### ISSUE TITLE
Remove .vscode folder unless there truly are shared settings

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/iotedgedev#144]
The .vscode folder should be removed from the project unless there are setting that really need to be shared across developers.  Not everyone will use the same extension set and want the same settings.

**Comment by jonbgallant** [comment]
I'm keeping it in for code formatting rules.

**Comment by jonbgallant** [comment]
template/launch.json is there for ease of debugging.

**Comment by WilliamBerryiii** [comment]
Double check then to see if there are settings that might not need/want to be universally applied ... like the autosave.

**Comment by jonbgallant** [comment]
Okay, thanks. That must have snuck in there. It should only be formatting.  Will remove.

**Comment by jongio** [comment]
Autosave removed.  Going to keep the barebones settings to pep8 settings.
