### ISSUE TITLE
Prompt users that Azure Credential Cache is being searched 

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/iotedgedev#145]
The following line can be quite alarming to users installing the tool via Pip package: 
`Retrieving Azure CLI credentials from cache...` 
It would be nice to have the tool prompt you to accept this action rather than automatically doing it without warning.

**Comment by WilliamBerryiii** [comment]
We say that after installing the tool via Pip, directly on a Win 10 Client Powershell terminal.

**Comment by jonbgallant** [comment]
What command did you run to get this?  I did pip install azure-iot-edge-dev-tool and do not see this.

**Comment by WilliamBerryiii** [comment]
`Pip install` then `iotedgedev init`
