### ISSUE TITLE
Add Build Options to module.json

### ISSUE THREAD

**Issue by jongio** [Azure/iotedgedev#163]
When calling docker build, we need to honor the buildOptions found in module.json

```
{
    "$schema-version": "0.0.1",
    "description": "",
    "image": {
        "repository": "shenweiotregistry.azurecr.io/samplemodule",
        "tag": {
            "version": "0.0.1",
            "platforms": {
                "amd64": "./Dockerfile", 
                "amd64.debug": "./Dockerfile.amd64.debug",
                "arm32v7": "./Dockerfile.arm32v7",
                "windows-amd64": "./Dockerfile"
            }
        },
        "buildOptions": [
            "--add-host=github.com:192.30.255.112",
            "--add-host=ports.ubuntu.com:91.189.88.150"
        ]
    },
    "language": "csharp"
}
```

**Comment by jonbgallant** [comment]
You will get this automatically when we move to creating the module dynamically as long as these are in the dynamic template

**Comment by jonbgallant** [comment]
Prereq: 
- Implement: iotedgedev module - create a new module
- iotedgedev solution uses 'iotedgedev module' to create the default module in the solution



iotedgedev build - needs to honor the buildOptions



Related: https://github.com/Azure/iotedgedev/issues/170

**Comment by jongio** [comment]
@LazarusX - Do you want to take this one?  I think this will be required for GA.

**Comment by LazarusX** [comment]
Sure.
