### ISSUE TITLE
[Errno 2] No such file or directory: '[...]\iotedgedev\.env'

### ISSUE THREAD

**Issue by yorek** [Azure/iotedgedev#164]
When running 

`iotedgedev init `

for the first time, just after having installed iotedgedev I get the following error:

`[Errno 2] No such file or directory: 'D:\\Work\\Personal\\_github\\iotedgedev\\.env'`

and the initialization process does not complete. I had to create a copy of `.env.tmp` and name it `.env` to have the process complete correctly.

The error is from `backup_dotenv` method in `EnvVars` class in envvars.py.

It seems that `iotedgedev solution` is not automatically invoked?

**Comment by jonbgallant** [comment]
Python version?
OS?
Are you running from the folder in your desc above or a diff folder?

**Comment by yorek** [comment]
Python 3.6.5
Windows 10 Pro
I was running `iotedgedev` from `D:\Work\Personal\_github\iotedgedev` (where I cloned the repository)

**Comment by jonbgallant** [comment]
Please try it from any other directory - other than the dir you cloned it into.  I have a feeling it has something to do with it being the root of the source.

**Comment by yorek** [comment]
Yep, it seems so, when running from the /home/iotedge folder in the docker container there are no problems. Closing this.
