### ISSUE TITLE
AZ IOT HUB apply-configuration needs hubname.

### ISSUE THREAD

**Issue by jongio** [Azure/iotedgedev#167]
If user has old version of az cli iot extension installed they get this: 

`az iot hub apply-configuration: error: argument --hub-name/-n is required
`

- add the -n parameter to the apply-configuration call.  you can get it in IOTHUB_CONNECTION_INFO.HostName

apply-configuration might need ONLY hubname, but HostName has [name].azuredevices.net.

Therefore, You might have to split the ConnectionString.HostName property and add a new property to that class called HubName.

**Comment by jonbgallant** [comment]
This only repros if you have az iot hub extension 0.4.2 or less, fixed in 0.4.3....so if you want to repro, you have to figure out a way to install 0.4.2
