### ISSUE TITLE
Incompatible azure.cli.core installation

### ISSUE THREAD

**Issue by Bougiefever** [Azure/iotedgedev#168]
I have azure cli version 2.0.31 installed. When I type the command "iotedgedev solution mysolution", I get an error from the line "from azure.cli.core import get_default_cli". In the azurecli.py python file, it cannot import get_default_cli. Do I have the wrong version of the azure cli installed? Which version should I be using?

**Comment by jonbgallant** [comment]
@Bougiefever - 

I was unable to repro with: 
- win10
- py2.7.14
- az 2.0.31
- az iot ext 0.4.3
- iotedgedev 0.81.0

Do your versions differ with above?

Jon
@paloukari

**Comment by jongio** [comment]
@Bougiefever  - Were you able to repro this?

**Comment by jongio** [comment]
Closing for now. Please reopen if you still see this issue.
