### ISSUE TITLE
Consider supporting a contains based search for subscriptions

### ISSUE THREAD

**Issue by druttka** [Azure/iotedgedev#177]
Related to #174.

Consider supporting a contains based search for the Azure subscription. We currently support searching by name, but given these subscriptions, the user experience is more streamlined if they can say "jon" instead of "Azure Account - j".

"Azure Account - david"
"Azure Account - jon"

**Comment by LazarusX** [comment]
Looks like this feature is already implemented by https://github.com/Azure/iotedgedev/blob/7425448297ef06f69350295bd4b614bd3dc3b55a/iotedgedev/azurecli.py#L272-L273?

**Comment by druttka** [comment]
@LazarusX yes, it looks like closing this issue fell through the cracks. Thanks for catching it. We decided to address "name contains" along with PR 174 https://github.com/Azure/iotedgedev/pull/174#issuecomment-396292881
