### ISSUE TITLE
Allow users to specify image repository when adding modules

### ISSUE THREAD

**Issue by LazarusX** [Azure/iotedgedev#215]

**Comment by jongio** [comment]
Should we default to ${CONTAINER_REGISTRY_SERVER}?

**Comment by LazarusX** [comment]
`${CONTAINER_REGISTRY_SERVER}` can be the default value, but is not enough to support multiple registries: https://github.com/Azure/iotedgedev/pull/193. Users should be able to specify alternative registries than `${CONTAINER_REGISTRY_SERVER}`.

**Comment by shizn** [comment]
Not a blocking issue.
