### ISSUE TITLE
Support context path in module.json to allow shared code

### ISSUE THREAD

**Issue by LazarusX** [Azure/iotedgedev#249]

**Comment by LazarusX** [comment]
Related: #207

**Comment by jongio** [comment]
Can we move this to GA since the 'shared code' customer is an iotedgedev user as well?

@adashen @LazarusX @shizn

**Comment by shizn** [comment]
Wei is already working on this for iotedgedev just after vscode. Could you help validate if the solution works for customer and share the feedback with us? Then we can safely move this one to GA. @jongio
