### ISSUE TITLE
Add copyright headers

### ISSUE THREAD

**Issue by LazarusX** [Azure/iotedgedev#268]

**Comment by jongio** [comment]
For every file? Did you see that this was required somewhere?

**Comment by LazarusX** [comment]
Yes...Please see https://docs.opensource.microsoft.com/releasing/copyright-headers.html

**Comment by jongio** [comment]
Okay, I got clarification on that a while back.  We don't need in every file.  Just in LICENSE.md

Please don't add to every file.

**Comment by LazarusX** [comment]
That's great. We already have https://github.com/Azure/iotedgedev/blob/master/LICENSE now. Is there anything else we need to do?

**Comment by jongio** [comment]
No
