### ISSUE TITLE
ERROR: Error: Install pypiwin32 package to enable npipe:// support

### ISSUE THREAD

**Issue by michaeljqzq** [Azure/iotedgedev#284]
Bugbash

iotedgedev push

**Comment by jongio** [comment]
@michaeljqzq - What version of Python?

**Comment by jongio** [comment]
Was this in an venv?

**Comment by jongio** [comment]
@michaeljqzq - Please install this and LMK if it fixes your issue:

`pip install -U git+https://github.com/jongio/iotedgedev.git@pypiwin32issue`

@LazarusX

**Comment by michaeljqzq** [comment]
Python version is 3.6.6
And I did not use venv. I used to use iotedgedev 0.81 and it works.
I have tried on the latest master branch and issue still exists

**Comment by jongio** [comment]
@michaeljqzq can you please clean your site-packages folder, except pip and try again?

**Comment by LazarusX** [comment]
Close due to lack of activities.

@michaeljqzq Please reopen if you can reproduce this issue.

**Comment by LazarusX** [comment]
I just reproduced this issue. Removing everything in site-packages except pip and pkg_resources worked for me.

**Comment by karncx** [comment]
`+1, came across this issue on a windows 10 machine and using Pipenv.`

**Comment by LazarusX** [comment]
@karncx  Sorry I cannot reproduce the issue with Pipenv. Could you share more detailed reproduce steps? Thanks.
