### ISSUE TITLE
[Bugbash] Error when run "iotedgedev monitor"

### ISSUE THREAD

**Issue by adashen** [Azure/iotedgedev#285]
- iotedgedev Version: 1.0 bugbash
- Python Version: 3.6 
- Development machine OS Version: windows
- IoT Edge device OS Version: 1.0

Steps to Reproduce:

1. Run "iotedgedev start" to start an edge solution. And containers are started successfully 
2. Run "iotedgedev monitor" to monitor the message 
Error:
az iot hub: 'monitor-events' is not in the 'az iot hub' command group. See 'az iot hub --help'.
ERROR: Failed to start monitoring events.

**Comment by LazarusX** [comment]
Updating Azure CLI IoT Extension fixes this issue: `az extension update --name azure-cli-iot-ext`
