### ISSUE TITLE
[BugBash] Cannot ctrl+c exit iotedge monitor

### ISSUE THREAD

**Issue by adashen** [Azure/iotedgedev#288]
- iotedgedev Version: 1.0 bugbash
- Python Version: 3.6
- Development machine OS Version: windows 10
- IoT Edge device OS Version: 1.0

Steps to Reproduce:
1. Run "iotedgedev monitor" to start monitor
2. Ctrl+c to exit. However cannot exit. And there is no message how to stop

**Comment by LazarusX** [comment]
I also encountered this as well. @jongio can you help take a look?

**Comment by LazarusX** [comment]
`KeyboardInterrupt` is intercepted: 
https://github.com/Azure/iotedgedev/blob/5c4652b20e5a84d312bcffee40fcf31c40ae76b2/iotedgedev/utility.py#L42-L43

Is there any reason for this?

**Comment by jongio** [comment]
Fixed with #302, @adashen or @LazarusX  - Can you verify?

**Comment by jongio** [comment]
1. When receiving msgs I hit CTRL+C and nothing happens.  I hit again and it terminates.
2. When not receiving msgs I hit CTRL+C and nothing happens.  I can't kill the process.  You can test this by calling iotedgedev monitor without calling iotedgedev setup and iotedgedev start first

**Comment by LazarusX** [comment]
Resolved by #301 and #306
