### ISSUE TITLE
[BugBash] "$edgeHub" is moved before "$edgeAgent" in deployment.json

### ISSUE THREAD

**Issue by formulahendry** [Azure/iotedgedev#290]
- Python Version: 2.7
- Development machine OS Version: Windiws 10

![image](https://user-images.githubusercontent.com/1050213/44450002-5b8f0a80-a622-11e8-906d-989193fd356d.png)

**Comment by LazarusX** [comment]
No. Deployment is successful.

**Comment by jongio** [comment]
Okay, I think should close unless there is a failure of some sort.

**Comment by LazarusX** [comment]
Close due to inactivity.
