### ISSUE TITLE
[bugbash]  iotedgedev start: returns Errno 2

### ISSUE THREAD

**Issue by katriendg** [Azure/iotedgedev#303]
- iotedgedev Version: 
 - Python Version: 2.7.14
- Pip Version: 18.0
- Development machine OS Version: Win Server 2016 Datacenter (Azure VM hosted)
- IoT Edge device OS Version: idem
Iotedgedev version: 0.81
All previous steps work fine up to this one. Could this be due to a missing pre-requisite? 
====
ERROR: Error: [Errno 2] No such file or directory: 'C:\\ProgramData\\iotedgehubdev\\config\\edgehub.json'
ERROR: Error while executing command: iotedgehubdev start -d config\deployment.json. Command '['iotedgehubdev', 'start', '-d', u'config\\deployment.json']' returned non-zero exit status 1
====

Content of C:\\ProgramData\\iotedgehubdev\\config folder: single file 'settings.ini' but no edgehub.json.

**Comment by jongio** [comment]
Thanks @katriendg  for testing!  Can you try to run iotedgedev setup before you run start?

**Comment by katriendg** [comment]
I thought I did but seems I skipped that step... So most probably that's the issue on my side.

However, I do get another issue now due to me running this on an Azure based VM.
1. The error when running _iotedgedev setup_ is the following:
===============================================
======== SETTING UP IOT EDGE SIMULATOR ========
===============================================

ERROR: Error: KWarg[hostname]:[myvmname].[uniqueid].ax.internal.cloudapp.net string length needs to greater than or equal to 1 and less than 64 characters.

2. I think this is where I noticed I had to do in the past (iotedgectl), was append this to my iotedgectl setup: 
--edge-hostname "[shortname]"

For GA, in the current config.yaml used by IoT Edge on that same machine (FYI), it has set this hostname setting:

###############################################################################
# Edge device hostname
###############################################################################
#
# Configures the environment variable 'IOTEDGE_GATEWAYHOSTNAME' injected into
# modules.
#
###############################################################################

**hostname: "[shortnameforvm]"**

**Comment by LazarusX** [comment]
@katriendg Can you try `iotedgedev setup -g [shortnameforvm]`? See `iotedgedev setup -h` for details.

**Comment by katriendg** [comment]
Thanks - yes this worked fine!
