### ISSUE TITLE
iotedgedev init fails on enter sub id

### ISSUE THREAD

**Issue by jongio** [Azure/iotedgedev#319]
1. iotedgedev init
2. when asked to choose subscription, only enter the first character of your sub id and hit enter.

![image](https://user-images.githubusercontent.com/2163001/45667760-50b78080-bacf-11e8-90d2-48be70e99dc1.png)

I think I got this because I have two subs that start with 'f'

It works if I use 2 chars because the second char is not the same in both subs that start with an f.

**Comment by LazarusX** [comment]
Duplicate of https://github.com/Azure/iotedgedev/issues/239?

**Comment by jongio** [comment]
Yes, dupe
