### ISSUE TITLE
I cannot find the requirements_dev.txt file

### ISSUE THREAD

**Issue by HenrikBach1** [Azure/iotedgedev#334]
Hi,

I'm following your documentation to setup a contributing environment: https://github.com/Azure/iotedgedev/blob/master/CONTRIBUTING.md

In step 4, you are refering to a file `requirements_dev.txt`. However, I cannot find the file. Can you give me an exact location of the file.

Thank you.

/Henrik

**Comment by jongio** [comment]
I see it in the root of the repo: https://github.com/Azure/iotedgedev/blob/master/requirements_dev.txt

**Comment by jongio** [comment]
Looking forward to your contributions! LMK if you run into any other issues.
