### ISSUE TITLE
Creds are printed in logs

### ISSUE THREAD

**Issue by jongio** [Azure/iotedgedev#343]
I think this is iotedgehubdev, but not sure...

Seeing this in logs when I run tox.

We shouldn't be printing sensitive info in logs.

```
EdgeHubConnectionString=HostName=jongiotfree.azure-devices.net;GatewayHostName=;DeviceId=edge1;ModuleId=target;SharedAccessKey=
EdgeModuleCACertificateFile=/var/lib/iotedgehubdev/certs/edge-device-ca/cert/edge-device-ca.cert.pem
```

**Comment by LazarusX** [comment]
Yes. This comes from the `iotedgehubdev modulecred` command (https://pypi.org/project/iotedgehubdev/), and the connection string is for developers to connect their module code to the local Edge Hub. The [local debug experience](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-develop-csharp-module#launch-and-debug-module-code-without-container) relies on this command.

This connection string is only on the module level, and only valid the for the corresponding edgeHub instance. `iotedgehubdev` is a neutral tool, so we made to trade-off to simply output it. Edge developers can manually copy it, redirect it to a file, set the environment variables, or read it from subprocess.
