### ISSUE TITLE
Failed to create java solution on windows

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/iotedgedev#344]
- iotedgedev Version: 1.0.0rc0
- Python Version: Python2.7 Python3.6 Python 3.7
- Pip Version: 9.0.3
- Development machine OS Version: Windows10
- IoT Edge device OS Version: Windows10
- Impacted platform: windows

Steps to Reproduce:

1. Install JDK 11
2. Install Maven 3.5.4
3. Run command "iotedgedev new test_solution -m filtermodule -t java"

Error message:
ADDING MODULE FILTERMODULE

ERROR: Error: [Error 2] The system cannot find the file specified
ERROR: Error while executing command: iotedgedev solution add filtermodule --template java --group-id com.edgemodule. Command '['iotedgedev', 'solution', 'add', 'filtermodule', '--template', 'java', '--group-id', 'com.edgemodule']' returned non-zero exit status 1
AZURE IOT EDGE SOLUTION CREATED

Execute 'cd test_solution' to navigate to your new solution.

**Comment by jongio** [comment]
@neil-yechenwei - Thanks a lot for submitting this.  I ran into the same thing today as well. I have a PR for a fix https://github.com/Azure/iotedgedev/pull/339 Which should hopefully get merged within the next 24 hrs.  

If you'd like to test it before then, you can do so via installing from my fork:
`pip install git+git://github.com/jongio/iotedgedev.git#pipelinemods`

**Comment by LazarusX** [comment]
Thanks @jongio for the quick fix. I was in head-down mode for the Tech Summit demo these two weeks. Actually @neil-yechenwei is our colleague who helps do manual test. 

@neil-yechenwei Neil could you help verify if Jon's fix works for you?
