### ISSUE TITLE
Failed to create c solution on mac os x

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/iotedgedev#345]
- iotedgedev Version: 1.0.0rc0
- Python Version: Python2.7 Python3.6 Python3.7
- Pip Version: 18.1
- Development machine OS Version: mac os high sierra 10.13.6
- IoT Edge device OS Version: mac os high sierra 10.13.6

Steps to Reproduce:
1. Run command "iotedgedev new test_solution -m filtermodule -t c"

Error message:
ADDING MODULE FILTERMODULE

ERROR: Error: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>
ERROR: Error while executing command: iotedgedev solution add filtermodule --template c. Command '['iotedgedev', 'solution', 'add', 'filtermodule', '--template', 'c']' returned non-zero exit status 1
AZURE IOT EDGE SOLUTION CREATED

Execute 'cd test_solution' to navigate to your new solution.

**Comment by LazarusX** [comment]
The macOS built-in Python is bundled with an old version of OpenSSL. Please use the ones installed with Homebrew instead.
