### ISSUE TITLE
Failed to push to local registry

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/iotedgedev#347]
- iotedgedev Version: 1.0.0rc0
- Python Version: Python2.7 Python3.6 Python3.7
- Pip Version:18.1
- Development machine OS Version: Windows10/Ubuntu18.04/Mac os high sierra 10.13.6
- IoT Edge device OS Version: Windows10/Ubuntu18.04/Mac os high sierra 10.13.6

Steps to Reproduce:
1. iotedgedev new test_solution -m filtermodule -t csharp
2. In .env file, update the CONTAINER_REGISTRY_SERVER with “localhost:5001”
3. Make sure there is no local docker registry in your machine (docker rm -f registry)
4. Run "iotedgedev push"
5. It will throw below error message 1
6. In .env file, update the CONTAINER_REGISTRY_SERVER with “localhost:5000”
7. Run "iotedgedev push"
8. It will throw below error message 2
9. Run "iotedgedev push"
10. It push successfully.

error message 1:
```
INITIALIZING CONTAINER REGISTRY

REGISTRY: localhost:5001
Looking for local 'registry' container
Local 'registry' container not found
Looking for local 'registry' image
Local 'registry' image not found
Pulling 'registry' image
Running registry container

PUSHING DOCKER IMAGE: localhost:5001/filtermodule:0.0.1-amd64
The push refers to repository [localhost:5001/filtermodule]
ERROR: Error: Get http://localhost:5001/v2/: read tcp 127.0.0.1:52290->127.0.0.1:5001: read: connection reset by peer
(py36) v-cheye@ubuntu1804-test10:~/csharp/test_solution$
```

error message 2:
```
INITIALIZING CONTAINER REGISTRY

REGISTRY: localhost:5000
Looking for local 'registry' container
Local 'registry' container not found
Looking for local 'registry' image
Local 'registry' image not found
Pulling 'registry' image
Running registry container

PUSHING DOCKER IMAGE: localhost:5000/filtermodule:0.0.1-amd64
The push refers to repository [localhost:5000/filtermodule]
ERROR: Error: Get http://localhost:5000/v2/: EOF
(py36) v-cheye@ubuntu1804-test10:~/csharp/test_solution$
```

**Comment by LazarusX** [comment]
Looks like it will take a moment for the registry container to accept requests after it's running. 

Can you try the below steps:
1. `iotedgedev new test_solution -m filtermodule -t csharp`
1. In .env file, update the `CONTAINER_REGISTRY_SERVER` with “localhost:5001”
1. Make sure there is no local docker registry in your machine: `docker rm -f registry`
1. Run `iotedgedev push`, and you will see error message 1.
1. Wait for about 30 seconds, run `iotedgedev push` again. Does the command run successfully?

**Comment by LazarusX** [comment]
I just filed a PR to fix this issue. You can try it with `pip install git+git://github.com/Azure/iotedgedev.git#ray-lr`

**Comment by neil-yechenwei** [comment]
After applied the fix and set the port as 5001 and 5000, it can push images to local registry successfully. I just verified on windows10 with linux container and python version is 3.7.

**Comment by neil-yechenwei** [comment]
After applied the fix and set the port as 5001 and 5000, it can push images to local registry successfully. I also verified on ubuntu1804 and mac os x 10.13.6 with linux container and python version is 3.7.
