### ISSUE TITLE
Createoptions fails to create mount to windows path

### ISSUE THREAD

**Issue by dominicloria** [Azure/iotedgedev#368]
- iotedgedev Version: 1.1.0
- Python Version:
- Pip Version:
- Development machine OS Version: Windows 10
- IoT Edge device OS Version: NA
- Docker for windows - linux containers

Steps to Reproduce:

1. Add entry in deployment.template.json:
 "createOptions": {
                "HostConfig": {
                  "Mounts": [{ "Type": "bind", "Source": "c:/test", "Target": "/test"}]
                }

2. Resultant  /var/lib/iotedgehubdev/data/docker-compose.yml entry:
 volumes:
    - source: c:/test
      target: /test
      type: bind

3. run envronment from with container:
iotedgedev@f6e7da7944e4:/home/iotedge$ sudo iotedgedev start --setup --file config/deployment.amd64.json

and........module fails

 Cannot create container for service xxx: invalid mount config for type "bind": invalid mount path: c:/test mount path must be absolute

seams as though docker-compose cannot handle this within container - tried docker-compose example and does not work

How do I resolve this issue - and will this issues occur on actual iot-edge device ?

Cheers

**Comment by LazarusX** [comment]
Thanks for reporting this issue. Based on you log, I suppose you are running the iotedgedev container.

The container is based on Linux, and docker-compose is in side the container. The source path `c:/test` does not follow the Linux absolute path pattern. That is why docker-compose failed.

To work around, can you try below steps:
1. Map your `c:/test` to the iotedgedev container, e.g.: `docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v c:/temp/iotedge:/home/iotedge c:/test:/test microsoft/iotedgedev`
2. In your create options, map again from the path in iotedgedev container to your destination, e.g.`"Mounts": [{ "Type": "bind", "Source": "/test", "Target": "/test"}]`

**Comment by dominicloria** [comment]
Thanks for the reply,

Yes, I have tried this scenario.

Unfortunately this did not work for me either. 

ERROR: for xxx Cannot create container for service xxx: invalid mount config for type "bind": bind source path does not exist: /test

Does this solution work for you ? 
Even if it does, how would this be established on a device with:
Windows IoT Enterprise
Docker for Windows
Linux Containers
IotEdge

Cheers

**Comment by LazarusX** [comment]
Thanks. I just took a deeper look and indeed found similar issues with nested binds and Docker-in-Docker scenario. I have filed a issue on Docker for Windows' repo with simplified reproduce steps: https://github.com/docker/for-win/issues/3091/. Alternately, you can try setting up the dependencies manually by following the wiki (https://github.com/Azure/iotedgedev/wiki/manual-dev-machine-setup).

Windows IoT support is still in progress. Please stay tuned. Thanks!

**Comment by blackchoey** [comment]
@dominicloria This issue has been fixed by our dependencies. I tried with iotedgehubdev 0.13.0 and docker desktop 2.1.0.1 (engine 19.03.1). This issue no longer exists.
I'm going to close this issue. Feel free to open new issues if you meet other problems. Thanks.
