### ISSUE TITLE
Unable to get device or hub Connection Strings from module

### ISSUE THREAD

**Issue by dominicloria** [Azure/iotedgedev#370]
- iotedgedev Version: latest
- Python Version:
- Pip Version:
- Development machine OS Version:  Windows
- IoT Edge device OS Version: latest
- Container version

Steps to Reproduce:

1. Configure the following entries in the .env file:
IOTHUB_CONNECTION_STRING="HostNa.........g3DsZwe4="
DEVICE_CONNECTION_STRING="HostNam...........NeKTnISk="

2. Try to obtain runtime values from environment within a c# module:
            // The Edge runtime gives us the connection string we need -- it is injected as an environment variable
            Console.WriteLine($"EdgeHubConnectionString = {Environment.GetEnvironmentVariable("EdgeHubConnectionString")}");
            Console.WriteLine($"IotHubConnectionString = {Environment.GetEnvironmentVariable("IotHubConnectionString")}");
            Console.WriteLine($"IOTEDGE_DEVICEID = {Environment.GetEnvironmentVariable("IOTEDGE_DEVICEID")}");
            Console.WriteLine($"IOTEDGE_MODULEID = {Environment.GetEnvironmentVariable("IOTEDGE_MODULEID")}");
            Console.WriteLine($"IOTEDGE_MODULEGENERATIONID = {Environment.GetEnvironmentVariable("IOTEDGE_MODULEGENERATIONID")}");
            Console.WriteLine($"IOTEDGE_AUTHSCHEME = {Environment.GetEnvironmentVariable("IOTEDGE_AUTHSCHEME")}");
            Console.WriteLine($"IOTEDGE_GATEWAYHOSTNAME = {Environment.GetEnvironmentVariable("IOTEDGE_GATEWAYHOSTNAME")}");
            Console.WriteLine($"IOTEDGE_IOTHUBHOSTNAME = {Environment.GetEnvironmentVariable("IOTEDGE_IOTHUBHOSTNAME")}");
            Console.WriteLine($"EdgeModuleCACertificateFile = {Environment.GetEnvironmentVariable("EdgeModuleCACertificateFile")}");
            Console.WriteLine("###### ALL ENV VARIABLES #######");
            var env = Environment.GetEnvironmentVariables();
            foreach ( var key in env.Keys)
            {
                Console.WriteLine($"{key} = {env[key]}");
            }

3. Unable to obtain Device Connection String - only EdgeHubConnectionString has value

**Comment by dominicloria** [comment]
ModuleClient does not support all functionality that DeviceClient does.

* Need to update device twin
* need to perform file upload
* possibly other functionality

I have found no  C# examples of how to perform these tasks from a module.

**Comment by LazarusX** [comment]
Got your point. For your requirement, you need to maintain the device connection string yourself. For example, you can set the device connection string as an environment variable in the deployment manifest, and then create device client with it in your module code. Below is an example deployment manifest snippet:
```json
  "tempSensor": {
    "type": "docker",
    "settings": {
      "image": "myregistry.azurecr.io/tempsensor:1.0",
      "createOptions": ""
    },
    "env": {
      "DEVICE_CONNECTION_STRING": {
          "value": "HostNa.........g3DsZwe4="
      }
    },
```

**Comment by blackchoey** [comment]
@dominicloria Please refer @LazarusX 's suggestion in your problem and let us know if you need further assistant.

**Comment by blackchoey** [comment]
@dominicloria We haven't hear from you for a while. I'm going to close this issue. Feel free to open new issues if you have other questions.
