### ISSUE TITLE
iotedgedev genconfig applies lowercase on environment variables

### ISSUE THREAD

**Issue by cfroment** [Azure/iotedgedev#371]
### Problem
`iotedgedev genconfig` applies lowercase on environment variables when generating the deployment manifest from the template.

### Description
Our team is using the Git commit tag name as docker image label for the IoT edge module. This label is set as an environment variable in the `deployment.template.json`

When using the 'Generate IoT Edge Deployment Manifest' from the context menu in VS Code, the deployment manifest is generated with the docker image label in the right case (the tag `1.2.3-RC1` is used as-is for the docker image label).

When using the `iotedgedev genconfig` command, our Git commit tag becomes lowercase (`1.2.3-RC1` becomes `1.2.3-rc1`), which results in failed deployments, as the edgeAgent cannot fetch the images from the container registry.

### Suggested solution
Environment variables in uppercase should be allowed

Thank you for your help.

**Comment by LazarusX** [comment]
Thanks @cfroment for reporting this issue. I can reproduce this issue and a fix is being worked on.

**Comment by jongio** [comment]
Thanks for your quick response @LazarusX !  I've added comments to the PR.

**Comment by LazarusX** [comment]
We just released 1.2.0. Please help upgrade with `pip install --upgrade iotedgedev` and let us know whether it fixes your issue. Thanks!
