### ISSUE TITLE
Fail to run after new installation

### ISSUE THREAD

**Issue by LazarusX** [Azure/iotedgedev#373]
`pkg_resources.ContextualVersionConflict: (PyYAML 3.13 (c:\venv\lib\site-packages), Requirement.parse('pyyaml>=4.2b1'), {'azure-cli-core'})`

**Comment by LazarusX** [comment]
New error appeared on CI after upgrading to `pyyaml>=4,2b1` in https://github.com/Azure/iotedgedev/pull/372/commits/d6436e102ceccc0e2d54d602b80e5313b5481745:
```
pkg_resources.ContextualVersionConflict: (PyYAML 4.2b4 (/mnt/a/1/s/.tox/py37/lib/python3.7/site-packages), Requirement.parse('PyYAML<4,>=3.10'), {'docker-compose'})
```

**Comment by jongio** [comment]
Aren’t we using explicit versions for all dependencies? We shouldn’t run into these types of issues if so, right?

**Comment by LazarusX** [comment]
No, we aren't now.

I was considering locking the all dependency versions (https://github.com/Azure/iotedgedev/compare/ray-deps?expand=1) after reading [this piece](https://blog.miguelgrinberg.com/post/the-package-dependency-blues), but realized that there will be more version conflicts if the user installs iotedgedev in the global environment. I prefer specifying a max version of azure-cli-core (https://github.com/Azure/iotedgedev/pull/372/commits/4aed1c3854f5e1874e9df2388f18a84126c2c58c)

**Comment by LazarusX** [comment]
Specifying version ranges for all dependencies like docker-compose does (https://github.com/docker/compose/blob/master/setup.py#L32-L43) will definitely help, but it's surprising that azure-cli-core upgraded PyYAML to a new major beta version in its patch release.

**Comment by LazarusX** [comment]
Should be fixed by https://github.com/Azure/iotedgedev/pull/372
