### ISSUE TITLE
Failed to execute - Quickstart with IoT Edge Dev Container: 4. Build IoT Edge module images

### ISSUE THREAD

**Issue by DoychinDoychev** [Azure/iotedgedev#374]
- iotedgedev Version: 1.1.0
- Python Version: 3.6.6
- Pip Version: 18.1
- Development machine OS Version: MacOS 10.14.2
- IoT Edge device OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Go to [Quickstart with IoT Edge Dev Container](https://github.com/Azure/iotedgedev/wiki/quickstart-with-iot-edge-dev-container)
2. Follow steps 1,2,3
3. Follow step 4 `sudo iotedgedev build`
4. You should see 
```
=======================================
======== ENVIRONMENT VARIABLES ========
=======================================

Environment Variables loaded from: .env (/home/iotedge/edge2/.env)

==================================
======== BUILDING MODULES ========
==================================

BUILDING MODULE: filtermodule
PROCESSING DOCKERFILE: /home/iotedge/edge2/modules/filtermodule/Dockerfile.amd64
BUILDING DOCKER IMAGE: localhost:5000/filtermodule:0.0.1-amd64
Step 1/12 : FROM microsoft/dotnet:2.1-sdk AS build-env
ERROR: Error: Error parsing reference: "microsoft/dotnet:2.1-sdk AS build-env" is not a valid repository/tag: invalid reference format
```

At this point i have no idea what to do.

**Comment by LazarusX** [comment]
Hi @DoychinDoychev, thanks for reporting this issue!

The statement `FROM microsoft/dotnet:2.1-sdk AS build-env` requires the [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) feature Could you help try upgrading your Docker engine to the latest version and try again?

**Comment by DoychinDoychev** [comment]
Hi @LazarusX, thank you for reply.

It worked without any issues :)
