### ISSUE TITLE
"exec format error" when installing 

### ISSUE THREAD

**Issue by iAmoric** [Azure/iotedgedev#375]
- iotedgedev Version: 
- Python Version: 3.5.6
- Pip Version: pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
- Development machine OS Version: Raspberry Pi - Raspbian 
- IoT Edge device OS Version: Raspberry Pi - Raspbian 

Steps to Reproduce:

I need iotedgedev to build a iot edge module on arm platform. 
When I try to install it with
`sudo docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v ~/iotedge:/home/iotedge microsoft/iotedgedev`

I have the following error: 
> `standard_init_linux.go:207: exec user process caused "exec format error"`

I'm not sure it is related to iotedgedev but can you please help ? Thanks.

**Comment by LazarusX** [comment]
Hi @iAmoric, thanks for reporting this issue!

Currently the IoT Edge Dev Tool Container is only available for Linux/AMD64. You can set up and install iotedgedev manually (https://github.com/Azure/iotedgedev/wiki/manual-dev-machine-setup)

**Comment by iAmoric** [comment]
@LazarusX thanks.

"If you are using a separate Edge device, like a Raspberry Pi, you do not need to run all of these steps on your IoT Edge device, you can install and setup Edge runtime directly on the device". 
So it means if I have the runtime installed on my raspberry, iotedgedev is already installed ?

**Comment by LazarusX** [comment]
Your development machine and Edge device are the same Raspberry Pi, right? If this is the case, you need to run all the steps on Raspberry Pi.

**Comment by LazarusX** [comment]
More specifically, if you would like to *only* build, Step 1, 2, 6, 8, 10 should be enough.

**Comment by iAmoric** [comment]
Yes they are the same. 
Thanks I will try it!

**Comment by iAmoric** [comment]
But actually, I already have the edge runtime installed on my Pi. Do I still need to follow all the steps ?

**Comment by LazarusX** [comment]
Yes, iotedgedev is not part of the runtime.

**Comment by iAmoric** [comment]
Ok it's clearer. Thanks

**Comment by blackchoey** [comment]
I'm going to close this issue since it has been resolved. Feel free to open new issues for further questions.
