### ISSUE TITLE
Container does not start

### ISSUE THREAD

**Issue by smoms** [Azure/iotedgedev#378]
- iotedgedev Version: latest
- Python Version:
- Pip Version:
- Development machine OS Version:
- IoT Edge device OS Version:

Steps to Reproduce:

1. I have pulled the repo docker pull microsoft/iotedgedev
2. docker run  docker run microsoft/iotedgedev

but nothing starts. What is wrong? thanks

**Comment by LazarusX** [comment]
Hi @smoms, thanks for reporting this issue!

The IoT Edge Dev Tool Container is designed to be run interactively. Here is the command to run the container (before you run the container, you will need to create a local folder to store your IoT Edge solution files):
    
**Windows**
```
mkdir c:\temp\iotedge
docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v c:/temp/iotedge:/home/iotedge microsoft/iotedgedev
```

**Linux**
```
sudo mkdir /home/iotedge
sudo docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v ~/iotedge:/home/iotedge microsoft/iotedgedev
```

**macOS**
```
mkdir ~/iotedge
docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v ~/iotedge:/home/iotedge microsoft/iotedgedev
```

You can learn more in the Quickstart (https://github.com/Azure/iotedgedev#quickstart).

**Comment by smoms** [comment]
@LazarusX thanks. One more question, in the Azure IoT Hub Portal i can see the 2 modules tempSensor and filtermodule but all column status are N/A. Why is that? thanks

**Comment by LazarusX** [comment]
That is weird. Could you file an issue on https://github.com/Azure/iotedge/issues with more detailed steps or screenshots? Thanks!

**Comment by blackchoey** [comment]
@smoms I opened following issue on behalf of you: https://github.com/Azure/iotedge/issues/2146. Please discuss there to get your problem about Azure IoT Hub Portal fixed. Thanks.
