### ISSUE TITLE
[FR] CONTAINER_REGISTRY_SERVER supports "https://index.docker.io/v1"

### ISSUE THREAD

**Issue by formulahendry** [Azure/iotedgedev#395]
In such a case, my docker hub user name is 'junhan', and I am in an org callded 'teamA'.
Then, I should be able to use below setting to use `iotedgedev push` for both 'junhan'and  'teamA':

```
CONTAINER_REGISTRY_SERVER="https://index.docker.io/v1"
CONTAINER_REGISTRY_USERNAME="junhan"
CONTAINER_REGISTRY_PASSWORD="<junhan_pwd>"
```

**Comment by blackchoey** [comment]
Here's a workaround:
If you want to push following image to docker hub: `formulahendry/samplemodule:0.0.1`, please set as environment variables as:
`
CONTAINER_REGISTRY_SERVER="formulahendry"
CONTAINER_REGISTRY_USERNAME="junhan"
CONTAINER_REGISTRY_PASSWORD="<junhan_pwd>"
`

**Comment by blackchoey** [comment]
We need to consider how to support the docker hub scenario. The SERVER concept only applies to ACR.

**Comment by jongio** [comment]
Set SERVER to your docker hub username to upload to docker hub. See https://github.com/Azure/iotedgedev/blob/master/iotedgedev/template/.env.tmp

**Comment by jongio** [comment]
I confirmed that this works:

CONTAINER_REGISTRY_SERVER="jongallant"
CONTAINER_REGISTRY_USERNAME="jongallant"
CONTAINER_REGISTRY_PASSWORD="password"


Your server and username need to be the same and set to your dockerhub username.

**Comment by formulahendry** [comment]
So if I want to push to 'teamA', the setting should be like below?

```
CONTAINER_REGISTRY_SERVER="teamA"
CONTAINER_REGISTRY_USERNAME="junhan"
CONTAINER_REGISTRY_PASSWORD="<junhan_pwd>"
```

For 'teamB', I need:

```
CONTAINER_REGISTRY_SERVER_2="teamB"
CONTAINER_REGISTRY_USERNAME_2="junhan"
CONTAINER_REGISTRY_PASSWORD_2="<junhan_pwd>"
```

**Comment by jongio** [comment]
Do you mean "team" or "organization"?

I see in Docker Hub:

Organization -> Repositories
Organization -> Teams

And Teams have perms to Repositories



jongio Org:
![image](https://user-images.githubusercontent.com/2163001/60908896-ca248900-a231-11e9-91af-f64f3959529a.png)


Has teams:
![image](https://user-images.githubusercontent.com/2163001/60908913-d4468780-a231-11e9-974a-77cb89312f44.png)


And repositories:
![image](https://user-images.githubusercontent.com/2163001/60908936-df011c80-a231-11e9-9ef4-e2a124659738.png)


And you can give those teams permissions to repositories here:
![image](https://user-images.githubusercontent.com/2163001/60908976-f3ddb000-a231-11e9-821a-177be1574e91.png)

Or here: 
![image](https://user-images.githubusercontent.com/2163001/60909021-0952da00-a232-11e9-9e50-dfdaef78a723.png)



So it is not clear to me why you would want to push to a "team"...which leads me to believe that you mean organization.

If so, then it is:
```
CONTAINER_REGISTRY_SERVER="orgA"
CONTAINER_REGISTRY_USERNAME="junhan"
CONTAINER_REGISTRY_PASSWORD="<junhan_pwd>"
```

**Comment by formulahendry** [comment]
Yes, I mean organization.

So if there are two organizations, the settings would be as below, right?
```
CONTAINER_REGISTRY_SERVER="orgA"
CONTAINER_REGISTRY_USERNAME="junhan"
CONTAINER_REGISTRY_PASSWORD="<junhan_pwd>"
CONTAINER_REGISTRY_SERVER_2="orgB"
CONTAINER_REGISTRY_USERNAME_2="junhan"
CONTAINER_REGISTRY_PASSWORD_2="<junhan_pwd>"
CONTAINER_REGISTRY_SERVER_3="junhan"
CONTAINER_REGISTRY_USERNAME_3="junhan"
CONTAINER_REGISTRY_PASSWORD_3="<junhan_pwd>"
```

**Comment by jongio** [comment]
Yep

________________________________
