### ISSUE TITLE
Provide commands for combining and splitting modules from different repos

### ISSUE THREAD

**Issue by tristanbarcelon** [Azure/iotedgedev#407]
Hi iotedgedev team. We have a scenario that requires:

1. placing edge modules we develop in different git repositories
2. those that are placed in the same git repo are related and versioned together, as they are tailored for communicating with machines from a specific manufacturer or types of machinery from that same manufacturer
3. modules being deployed to a particular environment be composed from different repos
4. not all modules from the same git repo will be deployed since we only need modules for machinery that will be present at the plant. For example, there might be modules m1, m2, m3, m4 from one git repo but we only need to deploy m1 and m3.

We currently handle the scenario above by manually creating a "merged" deployment template from different repos. This is very tedious and error prone. Do you have suggestions on how we can achieve this in a more systematic way?

I was thinking along the lines of an iotedgedev cli command which would have following input parameters:
- 1 or more git repository root/path(s) with the expectation that the repo has checked out the correct branch (master or release-*)
- 1 or more module names
- full destination path including file name for the combined template
   We intend to place all combined templates for all existing target environments in one git repository and name the template files as follows: deployment.template.<plant>-<env>.json where <env> can be dev, stg, or prd while <plant> could be any well known 3-4 letter plant identifier.

The combined template ideally needs to contain:
- required elements of a deployment template such as the container registry/credential variables, edgeAgent/edgeHub versions (taking the newest version if there are multiple git repo roots provided)
- the routes that depend on or are defined for the module(s) being composed
- createOptions and desiredProperties if they exist, including the variable tokens

I haven't fully thought through the ramifications of having such a command to our ci/cd pipelines but I'm open to suggestions.

**Comment by blackchoey** [comment]
Hi @tristanbarcelon we had a discussion about your scenario and would like to learn more details from you. Could you share more information for following questions? It would be great if we can have a quick call about your scenario. Please let me know your available time if we can have a call.

Some details we're interested in:
1. You mentioned you're manually creating a "merged" deployment template from different repos. In this deployment template, are you referencing the actual module image url or the module image is still some kind of placeholder?
2. If one module has a newer version, will the new version being deployed to IoT Edge devices immediately or you have fixed deployment cadence for IoT Edge devices?
3. How do you manually creating a "merged" deployment template from different repos and what's the pain points in this process?

**Comment by tristanbarcelon** [comment]
Hi @blackchoey , thank you for reaching out. 

1. The merged deployment template is in the form imagerepo:tag though the tag might still be a placeholder to be manually replaced by user.

2. Any module that is upreved will initially be published in the container registry. When it is deployed is subject to the deployment cadence for that specific environment. For example, if manufacturing plant A has an immediate need to get this version rolled out to its STG and PRD environments, I foresee the need for us to update the deployment.planta.json with this newer tag. Now that I think about this, it would be nice to be able to have a subcommand that would uprev tags of specified modules to non-prelease values that are available from the container registry.

3. Right now the process for merging deployment templates from different repos requires copying and pasting selected modules and sections from these templates into one deployment template using Visual Studio Code. It is very error prone as one could easily miss routes that are dependent on or defined for the modules being selected. Likewise, the edgeHub and edgeAgent versions could be different but in this scenario, it might be just better to emit a warning and pick the latest out of the source templates and utilize that.

We are on US Eastern timezone so if we can schedule a meeting that includes our dev team, that will be greatly beneficial.

**Comment by blackchoey** [comment]
Thank you @tristanbarcelon for the detailed information. I will coordinate with my teammate and send you meeting request once we decided the time.

**Comment by blackchoey** [comment]
@tristanbarcelon I have sent meeting invitation to you. If the time doesn't work for you, please let me know so I can adjust the time accordingly.

**Comment by tristanbarcelon** [comment]
@blackchoey Just replied with a different proposed day. Would that work for your team?

**Comment by blackchoey** [comment]
@tristanbarcelon Glad to talk with your team about your IoT Edge DevOps scenarios. As we discussed offline, please refer the suggested practices in the [IoT Edge CICD Deep Dive](https://channel9.msdn.com/Shows/Internet-of-Things-Show/Deep-Dive-Using-CICD-to-Deploy-IoT-Edge-Modules-with-Confidence). I'm going to close this issue. If you have further questions on iotedgedev, feel free to open new issues here.
