### ISSUE TITLE
docker.io image is severly out of date.  Does not work with current Azure IoT hub json replies.

### ISSUE THREAD

**Issue by robinmholt** [Azure/iotedgedev#408]
Steps to Reproduce:

1.  Follow steps in your wiki at https://github.com/Azure/iotedgedev/wiki/quickstart-with-iot-edge-dev-container and you will encounter a failure in step three 'iotedgedev init'.

Looking at this further, the docker.io container marked as microsoft/iotedgedev:latest was built on September 10, 2019, but it was built with sources from the v1.3.0 tag instead of the most recent release at the time which should have been v2.0.1.  It also appears the master branch has moved onto the v2.0.2 version, but there is no tag for that yet, so I am not understanding the release process.  I don't know what I should see, but I expect the microsoft/iotedgedev:latest to have at least v2.0.1 or potentially v2.0.2.

**Comment by blackchoey** [comment]
@robinmholt Thanks for reporting this issue. microsoft/iotedgedev:latest now points to v2.0.2, please try again. Feel free to let us know if you meet further problems.
