### ISSUE TITLE
issue with 'cs' keyerror #388

### ISSUE THREAD

**Issue by gerhard67** [Azure/iotedgedev#409]
In the actual version of https://hub.docker.com/_/microsoft-iotedge-iotedgedev the issue #388 is back 
1.
2.

**Comment by blackchoey** [comment]
Hi @gerhard67 , microsoft/iotedgedev:latest is now pointed to v2.0.2, which should addressed the issue. Please try again.

**Comment by blackchoey** [comment]
@gerhard67 We haven't heard from you for a while. I'm going to close this issue and feel free to open new issues if you meet other problems.
