### ISSUE TITLE
Wrong instruction to `iotedgedev iothub setup` with extra flags.

### ISSUE THREAD

**Issue by davidzwa** [Azure/iotedgedev#417]
- iotedgedev Version: 2.1.0
- Python Version: 3.6.9
- Pip Version: 19.3.1
- Development machine OS Version: Windows 10 Pro, build 18363
- IoT Edge device OS Version: 1.0.8

Steps to Reproduce:

1. Install according to quick-start.
2. Login to Azure via `sudo iotedgedev iothub setup`
3. Find iothub connection string issue
4. Resolve by calling the setup in the container:
https://github.com/Azure/iotedgedev/issues/392

Please adjust the documentation, because this is mentioned in quick setup...

**Comment by blackchoey** [comment]
@davidzwa Thanks for reporting. There's a bug in the command and it will be fixed in next version.
