### ISSUE TITLE
[Visual Studio 2019] Add modules from own registry

### ISSUE THREAD

**Issue by robbertvanhove** [Azure/iotedgedev#420]
Currently, there is the possibility to add a custom C#/C module to the iotedge project OR an already existing module from the Azure Marketplace as shown below:

![image](https://user-images.githubusercontent.com/13966309/71474552-4b6dd900-27dc-11ea-9702-6f613f6e3f2c.png)

When I already programmed a specific custom module in another project, it is pushed to an Azure Container Registry. If I want to add that module, i can add it by modifying 'deployment.template.json':
![image](https://user-images.githubusercontent.com/13966309/71474651-ce8f2f00-27dc-11ea-8b49-782805bd81d1.png)

But I would like to be able to add my registry to some configuration, so I can see all existing modules which then can be added to the project by a click. (like it's done with the modules from the Azure Marketplace) Below is an example of what I mean

![image](https://user-images.githubusercontent.com/13966309/71474800-773d8e80-27dd-11ea-9428-5f8c4476ef05.png)

**Comment by blackchoey** [comment]
You can now add modules from own registry with VS 2019 IoT Edge extension. Please update to latest version and try it out.
