### ISSUE TITLE
Update iotedgedev container release to include updated iotedgehubdev tool

### ISSUE THREAD

**Issue by jlorich** [Azure/iotedgedev#428]
If you use the iotedgedev container as a [Dev Container](https://code.visualstudio.com/docs/remote/containers) with VS Code it complains that the iotedgehubdev tool is not up to date.  Here's the warning:

>Update your 'iotedgehubdev' tool to the latest for the best experience for IoT Edge Simulator. (0.13.0 to 0.14.1)

If we could release an updated version that'd be great!

**Comment by blackchoey** [comment]
Thanks for the feedbacks. We will update this image.

**Comment by blackchoey** [comment]
Now the latest docker image has iotedgehubdev 0.14.1 installed. Please have a try.

**Comment by blackchoey** [comment]
Closing this issue. Feel free to open new issues if you meet other problems.
