### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by wmpauli** [Azure/iotedgedev#432]
on manual setup page:

```
C# module and C# Azure Functions module

Install .NET Core SDK.

    You need .NET Core SDK 2.1 or later to run it on ARM. There is no official document on installing .NET Core SDK 2.1 on ARM yet, but you can follow the ARM32v7 Dockerfile.

```

the link Dockerfile is dead. Also, is it required to use 2.1, or should one use the most recent version (currently 3.1)?

**Comment by jongio** [comment]
This should be the current equivalent: https://github.com/dotnet/dotnet-docker/blob/master/src/sdk/3.1/buster/arm32v7/Dockerfile

I haven't tested with 3.1, but it should work.

@blackchoey have you?

**Comment by wmpauli** [comment]
Thanks. I can confirm that it works with 3.1.

**Comment by blackchoey** [comment]
Thank you all. I have updated the link.
