### ISSUE TITLE
lowercase variables in module.json is not populated in Azure Devops build

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iotedgedev#438]
- iotedgedev Version: 2.1.6 (Azure Devops)
- Python Version: Azure Devops
- Pip Version: Azure Devops
- Development machine OS Version: Azure Devops
- IoT Edge device OS Version: Azure Devops

**Steps to Reproduce:**

With `module.json` as below. I have a variable defined as ACR to `xyz.azurecr.io`. The module CI build also works correctly in Azure Devops. **But if I change ${ACR} to ${acr} in module.json, the Azure Devops build fails. Why?** Is there some documentation on `module.json` for developers to follow. This may be a followup for [[1](https://github.com/Azure/iotedge/issues/61#issuecomment-461139106)] and documentation request more than a bug.

```json
{
  "$schema-version": "0.0.1",
  "description": "",
  "image": {
    "repository": "${ACR}/cameracapture:0.0.622603-amd64",
    "tag": {
      "version": "0.0.1",
      "platforms": {
        "amd64": "./Dockerfile.amd64",
      }
    },
    "buildOptions": [],
    "contextPath": "./"
  },
  "language": "python"
}
```

**Azure Devops Logs**

> 2020-10-14T12:22:13.9669043Z ##[section]Starting: Azure IoT Edge - Build module images
> 2020-10-14T12:22:13.9679150Z ==============================================================================
> 2020-10-14T12:22:13.9679581Z Task         : Azure IoT Edge
> 2020-10-14T12:22:13.9679906Z Description  : Build and deploy an Azure IoT Edge image
> 2020-10-14T12:22:13.9680242Z Version      : 2.4.4
> 2020-10-14T12:22:13.9680508Z Author       : Microsoft Corporation
> 2020-10-14T12:22:13.9680981Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
> 2020-10-14T12:22:13.9681438Z ==============================================================================
> 2020-10-14T12:22:14.5755018Z Building module images...
> 2020-10-14T12:22:14.5772232Z /home/vsts/work/1/s/IoTEdge /home/vsts/work/1/s
> 2020-10-14T12:22:45.5509603Z iotedgedev installed with version: version 2.1.6
> 2020-10-14T12:22:45.5510639Z 
> 2020-10-14T12:22:45.5547210Z [command]/usr/local/bin/iotedgedev build --file /home/vsts/work/1/s/IoTEdge/cameracapturedeployment.template.json --platform amd64
> 2020-10-14T12:22:45.5548080Z 
> 2020-10-14T12:22:45.6272723Z /usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
> 2020-10-14T12:22:45.6274486Z   from cryptography import x509
> 2020-10-14T12:22:45.6274954Z 
> 2020-10-14T12:22:45.7376861Z 
> 2020-10-14T12:22:45.7378361Z =======================================
> 2020-10-14T12:22:45.7378807Z 
> 2020-10-14T12:22:45.7379304Z ======== ENVIRONMENT VARIABLES ========
> 2020-10-14T12:22:45.7379777Z =======================================
> 2020-10-14T12:22:45.7380136Z 
> 2020-10-14T12:22:45.7381070Z .env file not found on disk. Without a file on disk, you must specify all Environment Variables at the system level. (/home/vsts/work/1/s/IoTEdge/.env)
> 2020-10-14T12:22:45.7381711Z 
> 2020-10-14T12:22:45.7438860Z 
> 2020-10-14T12:22:45.7439810Z Welcome to iotedgedev!
> 2020-10-14T12:22:45.7441077Z -------------------------
> 2020-10-14T12:22:45.7441561Z Telemetry
> 2020-10-14T12:22:45.7443011Z ---------
> 2020-10-14T12:22:45.7443543Z The iotedgedev collects usage data in order to improve your experience.
> 2020-10-14T12:22:45.7444113Z The data is anonymous and does not include commandline argument values.
> 2020-10-14T12:22:45.7444964Z The data is collected by Microsoft.
> 2020-10-14T12:22:45.7445722Z 
> 2020-10-14T12:22:45.7446617Z You can change your telemetry settings by updating 'collect_telemetry' to 'no' in /home/vsts/.iotedgedev/setting.ini
> 2020-10-14T12:22:45.7447489Z 
> 2020-10-14T12:22:45.7447780Z 
> 2020-10-14T12:22:45.7448162Z Welcome to iotedgedev!
> 2020-10-14T12:22:45.7448780Z -------------------------
> 2020-10-14T12:22:45.7449187Z Telemetry
> 2020-10-14T12:22:45.7449721Z ---------
> 2020-10-14T12:22:45.7450204Z The iotedgedev collects usage data in order to improve your experience.
> 2020-10-14T12:22:45.7450784Z The data is anonymous and does not include commandline argument values.
> 2020-10-14T12:22:45.7451291Z The data is collected by Microsoft.
> 2020-10-14T12:22:45.7451656Z 
> 2020-10-14T12:22:45.7452773Z You can change your telemetry settings by updating 'collect_telemetry' to 'no' in /home/vsts/.iotedgedev/setting.ini
> 2020-10-14T12:22:45.7453358Z 
> 2020-10-14T12:22:45.7453671Z 
> 2020-10-14T12:22:45.7453960Z 
> 2020-10-14T12:22:45.7454364Z ==================================
> 2020-10-14T12:22:45.7456068Z ======== BUILDING MODULES ========
> 2020-10-14T12:22:45.7456559Z ==================================
> 2020-10-14T12:22:45.7456850Z 
> 2020-10-14T12:22:45.7457099Z 
> 2020-10-14T12:22:45.7598520Z PROCESSING DOCKERFILE: /home/vsts/work/1/s/IoTEdge/modules/CameraCapture/Dockerfile.amd64
> 2020-10-14T12:22:45.7599244Z 
> 2020-10-14T12:22:45.7600362Z BUILDING DOCKER IMAGE: ${acr}/cameracapture:0.0.622603-amd64
> 2020-10-14T12:22:45.7600766Z 
> 2020-10-14T12:22:45.7826824Z ERROR: 500 Server Error: Internal Server Error ("invalid reference format")
> 2020-10-14T12:22:45.7827660Z 
> 2020-10-14T12:22:45.8202129Z ##[error]Error: The process '/usr/local/bin/iotedgedev' failed with exit code 1
> 2020-10-14T12:23:46.3543035Z ##[section]Finishing: Azure IoT Edge - Build module images

**Comment by konichi3** [comment]
Is this still an issue and have you explored any workaround?

**Comment by kiranpradeep** [comment]
This is still an issue.

**Comment by marianan** [comment]
Hello @kiranpradeep , thanks for reporting this issue. There are 2 datapoints that would help narrow down where the bug is coming from:
1. Could you please try to reproduce the issue using https://github.com/Azure/iotedgedev tool and share if the symptoms persist?
2. Could you build your module using docker build and share if the symptoms persist?

**Comment by kiranpradeep** [comment]
1. The issue is not reproducible when I build locally (Ubuntu 18.04) with iotedgedev 
2. The issue is not also on present on the docker build.

**Comment by cindydeng1998** [comment]
Hello @kiranpradeep, it seems like Azure Devops is case sensitive when it comes to variable names, which is why you didn't run into the issue running the iotedgedev tool locally or on the docker build. This link might be of interest to you: [Define Variables - Azure Pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)

Since this is an issue with Azure Devops and out of the scope of this repo, we will mark this issue as closed. Thank you!
