### ISSUE TITLE
Enable DOCKER_BUILDKIT

### ISSUE THREAD

**Issue by goatwu1993** [Azure/iotedgedev#440]
My usage
1. Using iotedgedev build image (Azure pipelines).
2. Building arm64v8 docker images
3. Using python, with packages written in requirements

Because most python package(e.g. numpy) that is written in C does not provide arm64 wheels, they will fall back to compile c code. The first install can be really fast.

However, once the install is complete, a wheel is cached, and installing after became really fast. DOCKER_BUILDKIT will help you cache the wheels. However, I can not find iotedgedev provide an option of opening DOCKER_BUILDKIT.

**Comment by marianan** [comment]
Hi @goatwu1993 , thank you for your suggestion. At this time we are not planning on adding support for leveraging Docker buildkit. Please let us know if this is blocking any of your use cases.
