### ISSUE TITLE
Many containers left behind with every start

### ISSUE THREAD

**Issue by eavanvalkenburg** [Azure/iotedgedev#461]
- iotedgedev Version: 2.2.0
- Python Version: 3.6.9
- Pip Version: 20.3.3
- Development machine OS Version: MacOS in vscode devcontainer
- IoT Edge device OS Version: 

Steps to Reproduce:

1. Running in a container (in my case I created a devcontainer definition for iotedgedev for use with vscode)
2. Every time I change something in my custom module, build, push and start I get several containers left behind, one called cert_helper and one per start with a random name.

I am developing a custom module in python, so whenever I make a change in my code, I push that build to the local registry with `sudo iotedgedev push` and then run `sudo iotedgedev start -f ...` to start the solution again, could be that I just do it wrong!

**Comment by marianan** [comment]
Hello @eavanvalkenburg thanks for reporting this issue. The cert_helper is used by the simulator, we will investigate why it doesn't get cleaned up properly and will share updates when available. The issue is tracked in our backlog.

**Comment by marianan** [comment]
Hello @eavanvalkenburg, to remove the containers used by the simulator, the simulator needs to stop running first with this command - iotedgedev stop. To remove the containers used for building, use these 2 commands - "iotedgedev docker clean -c" and "iotedgedev docker clean -i".

In general, here is the recommended flow. People may decide to stop the simulator and cleanup containers. The readme is updated with this info as well [.](https://github.com/Azure/iotedgedev/pull/474)
iotedgedev build
iotedgedev push
iotedgedev start --setup --file config/deployment.amd64.json
iotedgedev monitor
iotedgedev stop
iotedgedev docker clean -c
iotedgedev docker clean -i
