### ISSUE TITLE
Devcontainer

### ISSUE THREAD

**Issue by eavanvalkenburg** [Azure/iotedgedev#462]
I created a version of this that works with the vscode devcontainer and to me it is a much clearer starting point, just clone the repo, open in vscode, it asks to open the devcontainer and off you go! I have created it here: https://github.com/eavanvalkenburg/iotedgedev-sample-python

Also would be good to update the python version inside the iotedgedev container to at least 3.9!

**Comment by marianan** [comment]
Hello @eavanvalkenburg thanks for sharing the devcontainer you created and for reporting the python version request. We are tracking in our backlog to update all tools to latest python version.

**Comment by eavanvalkenburg** [comment]
Good to hear, thanks!

**Comment by jongio** [comment]
@eavanvalkenburg - Very cool. Can you do a PR for the devcontainer?

**Comment by eavanvalkenburg** [comment]
@jongio off course! Where should it go, inside https://github.com/Azure/iotedgedev/tree/master/iotedgedev/template perhaps?

**Comment by jongio** [comment]
I think there are two things:
1. devcontainer for iotedgedev itself, should go in root of this repo at /
2. devcontainer for solutions created with iotedgedev, should go in template.  Please verify that the devcontainer carries over when a new solution is created.  At one point, I had to update the zip file as well, but I believe that zip creation is automated now.

**Comment by eavanvalkenburg** [comment]
Yeah this is a devcontainer for solutions (nr 2), So I'll have a look at what happens in the current script and zip!

**Comment by konichi3** [comment]
@eavanvalkenburg 
A few months ago, we have added the [devcontainer ](https://github.com/Azure/iotedgedev/tree/master/.devcontainer)for the iotedgedev tool. 

Please take a look. Feel free to submit PR if there are enhancements that you can think of.

**Comment by eavanvalkenburg** [comment]
Thanks for the callout @konichi3 I'll have a look!
