### ISSUE TITLE
Dynamically Use Device Tags in IoT Edge Module Environment Variables

### ISSUE THREAD

**Issue by niemilkm** [Azure/iotedgedev#464]
### Overview ###
I am using IoT Hub and IoT Edge as container management across my fleet of gateways. The IoT Edge Module that I am using is coming from the Azure Marketplace and each deployment of it requires a unique access key and secret (as environment variables) that I get from a 3rd party application. Deploying these modules 1 by 1 to each gateway works no problem since I can configure a new unique Access and Key per gateway/module.

### Problem ###
If I want to do this by creating a Deployment in IoT Hub, when I go to configure my Azure Marketplace module environment variables it only gives me the ability to enter one unique Access Key and Secret that will be deployed to all of my devices (but I need a 1 to 1 relationship between Access Key and Secret to gateway/module).

### Feature Request ### 
Allow device tags from edge devices to be used in the configuration of environment variables of edge modules in IoT Hub. This way in the deployment (Edge Module configuration of environment variables) I could specify something like tags.access_key and tags.access_secret and when this edge module is deployed to each gateway (via deployment) that this access key and access secret is looked up from the device tags and entered automatically into the edge module on deployment of each module/gateway.

If there is a way to do this already (by same means as above or an entirely different way), please let me know. Thank you in advance.

**Comment by marianan** [comment]
@niemilkm - thanks for filing this request. Could you clarify what is your use case - are you trying to use the tags for targeting devices during deployment?

**Comment by niemilkm** [comment]
I understand how to add tags to an edge device in IoT Hub and then how to do a deployment and use those tags to select some subset of my edge devices.

The IoT Module that I am deploying has an environment variable called ACCESS_KEY. I get this ACCESS_KEY from a 3rd party service and each module that is deployed has to have a unique ACCESS_KEY. If I deploy these modules 1 at a time, this is easy to do because I add the module to my device, click on the module, go to environment variables, and type in that unique ACCESS_KEY.

If I want to do this at scale, I need a way in the deployment to pass a unique ACCESS_KEY to the module that is going to be deployed for each gateway. Let's say in my deployment I state tags.location.floor = '1' and that pulls in two devices for this module to be pushed down. Each module has to have a unique ACCESS_KEY environment variable value. If it uses the same ACCESS_KEY for both devices then it won't work.

My suggestion on a way to get around this, and again I am open to better ways, is to allow me to specify on my Edge Device in IoT Hub a tag that can then be dynamically referenced in the module on deployment. For example, I would create a device tag like so, tags.access_key and each Edge Device in IoT Hub would have a unique value there. Then in the deployment when I select my IoT Module, and then I click to configure it, and go to Environment Variables, I could then enter something like %%tags.access_key%% for the environment variable of ACCESS_KEY and on deployment to each device, it would fill in the correct value of the access key for each module from the IoT Edge tag access key.

Does that make sense?

**Comment by darobs** [comment]
Hi @niemilkm,

The Azure IoT Edge team does see value in this. We suggest all features requests be submitted to [UserVoice](https://aka.ms/iotedge-suggestion), but may I suggest you upvote and append your suggestion to this particular request?

[Allow for placeholder variables in IoT Edge deployment templates](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/36817912-allow-for-placeholder-variables-in-iot-edge-deploy)

Thanks,
DAVE!!!

**Comment by mhshami01** [comment]
@niemilkm - Please follow the guidance from Dave to see if the request is already in the suggestion box and upvote accordingly. I will now mark this issue closed.

Sincerely,
--Haitham
