### ISSUE TITLE
 Could not initialize module runtime

### ISSUE THREAD

**Issue by pospospos2007** [Azure/iotedgedev#467]
I was trying to run runtime iot edge on my Macbook 

OS 10.13

Docker version 19.03.13

Steps to Reproduce:

I pulled your code from master and run

1. run:
./iotedgedev/docker/runtime/build-container.sh

2. setup env value IOT_DEVICE_CONNSTR

3. run:
./iotedgedev/docker/runtime/run-container.sh

4. Logs from console:

<6>2021-04-07T17:09:58Z [INFO] - Using config file: /etc/iotedge/config.yaml
<6>2021-04-07T17:09:58Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2021-04-07T17:09:58Z [INFO] - Version - 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)
<6>2021-04-07T17:09:58Z [INFO] - Using runtime network id azure-iot-edge
<6>2021-04-07T17:09:58Z [INFO] - Initializing the module runtime...
<6>2021-04-07T17:09:58Z [INFO] - Initializing module runtime...
<4>2021-04-07T17:09:58Z [WARN] - Could not initialize module runtime
<4>2021-04-07T17:09:58Z [WARN] -        caused by: Container runtime error
<4>2021-04-07T17:09:58Z [WARN] -        caused by: an error occurred trying to connect: Connection refused (os error 111)
<4>2021-04-07T17:09:58Z [WARN] - Could not initialize module runtime
<4>2021-04-07T17:09:58Z [WARN] -        caused by: Container runtime error
<4>2021-04-07T17:09:58Z [WARN] -        caused by: an error occurred trying to connect: Connection refused (os error 111)
<3>2021-04-07T17:09:58Z [ERR!] - The daemon could not start up successfully: Could not initialize module runtime
<3>2021-04-07T17:09:58Z [ERR!] -        caused by: Could not initialize module runtime
<3>2021-04-07T17:09:58Z [ERR!] -        caused by: Container runtime error
<3>2021-04-07T17:09:58Z [ERR!] -        caused by: an error occurred trying to connect: Connection refused (os error 111)
rrcs-71-42-212-22:runtime 

Any comment is appreciated.

**Comment by cindydeng1998** [comment]
@pospospos2007 Thank you for bringing this to our attention, we have added your issue to our backlog and will get back to you as soon as we can. Meanwhile, have you tried out the Quickstart portion of the tool? https://github.com/Azure/iotedgedev#quickstart

**Comment by marianan** [comment]
@pospospos2007 could you share the config.yaml file by running: docker exec iotedgec cat /etc/iotedge/config.yaml

**Comment by pospospos2007** [comment]
I fixed it by downgrade my docker to 2.1 
My docker was 3.0 previously.
