### ISSUE TITLE
Support for Visual Studio Code DevContainer

### ISSUE THREAD

**Issue by EliiseS** [Azure/iotedgedev#488]
Provide a `.devcontainer` folder in the source repository so that it makes it easier for contributors to get a working environment on their development machine. This would be a docker file with all the pre-requisites defined in it that could just be spun up when required. This would mean that the version of python and other libraries could be kept in step with the repo.

**References**
<https://code.visualstudio.com/docs/remote/containers>

If you'd be willing to accept this, I'd be more than happy to create a PR for it.

**Comment by marianan** [comment]
Hello @EliiseS thanks for your suggestion. Please go ahead and create a PR if you have a working version of the devcontainer folder. We will help you review and merge it.

**Comment by marianan** [comment]
@EliiseS thanks for your contribution. Your PR has been successfully merged. I am closing this issue.
