### ISSUE TITLE
Update docker image reference in the Wiki

### ISSUE THREAD

**Issue by vlad-ro** [Azure/iotedgedev#511]
Wiki suggest the following command to run the IoT Edge Dev Container:
```
mkdir c:\temp\iotedge
docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v c:/temp/iotedge:/home/iotedge microsoft/iotedgedev
```
However this results in:
```
Unable to find image 'microsoft/iotedgedev:latest' locally
docker: Error response from daemon: pull access denied for microsoft/iotedgedev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```
Looks like `microsoft/iotedgedev` needs to be replaced with `mcr.microsoft.com/iotedge/iotedgedev`.

Affected pages:
- https://github.com/Azure/iotedgedev/wiki/quickstart-with-iot-edge-dev-container
- https://github.com/Azure/iotedgedev/wiki/overview

**Comment by konichi3** [comment]
Thanks for the feedback. Fixed the command in two pages in Wiki described above.
