### ISSUE TITLE
$edgeHub startup RouteCompilationException

### ISSUE THREAD

**Issue by arnozeelmaekers** [Azure/iotedgedev#512]
Hey All,

I'm dealing with an error while trying to develop an IoT Edge module.

- iotedgedev Version: iotedgedev, version 3.3.0
- Python Version: Python 3.6.9
- Pip Version: pip 21.2.4 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
- Development machine OS Version: Windows 10 Version 21H1
- IoT Edge device OS Version: Windows 10 Version 21H1

Steps to Reproduce:

1. mkdir c:\temp\iotedge
2. docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v c:/temp/iotedge:/home/iotedge mcr.microsoft.com/iotedge/iotedgedev
3. Create new IoT project in Visual Studio with multiple modules
4. Change routing
5. Deploy the module using Visual Studio

Error received:
[helper.log](https://github.com/Azure/iotedgedev/files/7568860/helper.log)

Deployment.debug.template.json
[deployment.debug.template.txt](https://github.com/Azure/iotedgedev/files/7568871/deployment.debug.template.txt)

Any help fixing this error is much appreciated. If you need any additional information let me know.

With regards,
Arno Zeelmaekers

**Comment by yophilav** [comment]
Heyo @arnozeelmaekers !

Hope you're doign well so far. Thank you for the question!
From the `helper.log` lines: 
```
<6> 2021-11-19 08:23:57.252 +00:00 [INF] - MessageAckTimeoutSecs=30
Unhandled exception. System.AggregateException: One or more errors occurred. (Exception of type 'Microsoft.Azure.Devices.Routing.Core.Query.RouteCompilationException' was thrown.)
 ---> Compilation errors:
StartLine[1], StartColumn[160], EndLine[1], EndColumn[161], Severity[Error], Message: Syntax error.
```

I suspect there maybe an invalid json format somewhere in the `routes` section. Sure enough, in `deployment.debug.template.txt`
```
          "IdentityTranslationModuleToBoilerPlate": {
            "route": "FROM /messages/modules/IdentityTranslationModule/outputs/boilerplate/* INTO BrokeredEndpoint(\"/modules/ProtocolTranslationModuleBoilerplate/inputs/boilerplate\"",
            "priority": 0,
            "timeToLiveSecs": 1800
          },
```
there is a missing `)` for the BrokeredEndpoint.
Note: 

"route": "FROM /messages/modules/IdentityTranslationModule/outputs/boilerplate/* INTO BrokeredEndpoint(\"/modules/ProtocolTranslationModuleBoilerplate/inputs/boilerplate\"**)**",

**Comment by arnozeelmaekers** [comment]
Hey @yophilav 

God I feel so dumb now. Thanks so much!

With regards,
Arno Zeelmaekers

**Comment by yophilav** [comment]
It's all good! Have a nice day :)
