### ISSUE TITLE
Please update python3 version in mcr.microsoft.com/iotedge/iotedgedev

### ISSUE THREAD

**Issue by bqstony** [Azure/iotedgedev#532]
It would be nice to have a never version of python3 then actually. Somthing like 3.8 or more.

Actually is: 
```bash
$ docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock  mcr.microsoft.com/iotedge/iotedgedev:3.3.4
Unable to find image 'mcr.microsoft.com/iotedge/iotedgedev:3.3.4' locally
3.3.4: Pulling from iotedge/iotedgedev
Digest: sha256:335c491b60cf34a86cdd9da13eb1253d5874df869b9ec93328216ab0483c7763
Status: Downloaded newer image for mcr.microsoft.com/iotedge/iotedgedev:3.3.4
iotedgedev@894f25892d08:/home/iotedge$ python3 --version
Python 3.6.9
```

**Comment by konichi3** [comment]
Hi @bqstony 

Thank you for reporting. We are currently in midst of updating the py3 version in mcr images. We will let you know once we release the changes.

**Comment by mhshami01** [comment]
hello @bqstony,

Thank you for your contribution. Please try the following
docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock  mcr.microsoft.com/iotedge/iotedgedev:latest

**Comment by marianan** [comment]
Closing the issue, please update if symptoms persist.
