### ISSUE TITLE
Remove dupe log messages in `iotedgedev init`

### ISSUE THREAD

**Issue by beandrad** [Azure/iotedgedev#558]
- iotedgedev Version: v3.3.4
- Python Version: 3.9
- Pip Version: 22.0.4
- Development machine OS Version: Debian GNU/Linux 11 (bullseye)
- IoT Edge device OS Version: Debian GNU/Linux 11 (bullseye)

The `iotedgedev init` print some messages twice:

<img width="557" alt="Screenshot 2022-05-07 at 11 12 21" src="https://user-images.githubusercontent.com/67916678/167249974-b254c69c-d388-4ae6-8fb5-29fe44a91ced.png">

Steps to Reproduce:

1. Run `iotedgedev init`

**Comment by roel4ez** [comment]
ping @EliiseS
