### ISSUE TITLE
Other solution for genconfig which is marked as deprecated

### ISSUE THREAD

**Issue by martin-weber** [Azure/iotedgedev#588]
Hello,
We are using `iotedgedev genconfig` in a automation script which sets up the development environment in EFLOW. 
We generate the deployment manifest from a deployment template and use then the manifest with `az iot edge set-modules --content $deploymentManifestFilePath --device-id $deviceId --hub-name $iotHubName` to setup the required configuration.

`iotedgedev genconfig` is a great help for us as it reduces an error prone manual step in vscode to generate the deployment manifest from the template.

Now we see the warning: 
**DeprecationWarning: The command 'genconfig' is deprecated**

What is the suggested alternative to generate the deployment manifest from the deployment template?

We would greatly appreciate, if if this feature will not be deprecated or there is another solution to generate the deployment manifest from the template in a script.

Thanks a lot.

**Comment by marianan** [comment]
@martin-weber please use 'iotedgedev solution genconfig' instead. There is duplication of commands that we are trying to cleanup and we advise users to use the subgroup commands. At this time there is no change in functionality and both main and subcommands point to the same functionality.

**Comment by roel4ez** [comment]
see PR #593

**Comment by roel4ez** [comment]
@marianan @martin-weber this issue was resolved with #593

**Comment by martin-weber** [comment]
Thanks a lot for the clarification and the great tools.
