### ISSUE TITLE
[BUG] WSL2 installation on Ubuntu 20.04 - docker-compose and other dependent required package versions 

### ISSUE THREAD

**Issue by katriendg** [Azure/iotedgedev#591]
### Description

When installing the CLI tool using the below command, on Windows 10 Insider build, WSL2, Ubuntu 20.04.
`pip3 install iotedgedev`

Error message:
![image](https://user-images.githubusercontent.com/838216/193513665-9e9ea8c6-8768-4e7f-a560-d87feede4f64.png)

After the rest of the installation finishes, I seem to be able to use the commands of the CLI, create a new solution and project. However, unsure if due to the error message one of the subsequent commands might still fail.

### Expected behavior

Installation allows for existing packages to be >= rather than specific versions?

### Actual behavior

See error message described.

### Steps to Reproduce

Not sure this can be easily reproduced, other than setting up an environment with the same package versions as I have, for example with PyYAML 6.0, and portallocker 2.4.

### Environment

iotedgedev Version: version 3.3.5
Python version: Python 3.8.10
Pip3 version: pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
Development machine OS Version: Windows 10 WSL2 - Ubuntu 20.04
IoT Edge device OS Version: Ubuntu 20.4 (not applicable, not causing an issue)

**Comment by konichi3** [comment]
Closing as the [other issue](https://github.com/Azure/iotedgedev/issues/589) is resolved.

@katriendg Feel free to re-open if this issue still persists.
